const MedicalSpecialties = [
  { "Allergy and Immunology": null },
  {
    Anesthesiology: [
      "Critical Care Medicine",
      "Hospice and Palliative Care",
      "Pain Medicine",
      "Pediatric Anesthesiology",
      "Sleep Medicine",
    ],
  },
  {
    Dermatology: [
      "Dermatopathology",
      "Pediatric Dermatology",
      "Procedural Dermatology",
    ],
  },
  {
    "Diagnostic Radiology": [
      "Abdominal Radiology",
      "Breast Imaging",
      "Cardiothoracic Radiology",
      "Cardiovascular Radiology",
      "Chest Radiology",
      "Emergency Radiology",
      "Endovascular Surgical Neuroradiology",
      "Gastrointestinal Radiology",
      "Genitourinary Radiology",
      "Head and Neck Radiology",
      "Interventional Radiology",
      "Musculoskeletal Radiology",
      "Neuroradiology",
      "Nuclear Radiology",
      "Pediatric Radiology",
      "Radiation Oncology",
      "Vascular and Interventional Radiology",
    ],
  },
  {
    "Emergency Medicine": [
      "Anesthesiology Critical Care Medicine",
      "Emergency Medical Services",
      "Hospice and Palliative Medicine",
      "Internal Medicine",
      "Critical Care Medicine",
      "Medical Toxicology",
      "Pain Medicine",
      "Pediatric Emergency Medicine",
      "Sports Medicine",
      "Undersea and Hyperbaric Medicine",
    ],
  },
  {
    "Family Medicine": [
      "Adolescent Medicine",
      "Geriatric Medicine",
      "Hospice and Palliative Medicine",
      "Pain Medicine",
      "Sleep Medicine",
      "Sports Medicine",
    ],
  },
  {
    "Internal Medicine": [
      "Advanced Heart Failure and Transplant Cardiology",
      "Cardiovascular Disease",
      "Clinical Cardiac Electrophysiology",
      "Critical Care Medicine",
      "Endocrinology, Diabetes, and Metabolism",
      "Gastroenterology",
      "Geriatric Medicine",
      "Hematology",
      "Hematology and Oncology",
      "Infectious Disease",
      "Interventional Cardiology",
      "Nephrology",
      "Oncology",
      "Pediatric Internal Medicine",
      "Pulmonary Disease",
      "Pulmonary Disease and Critical Care Medicine",
      "Rheumatology",
      "Sleep Medicine",
      "Sports Medicine",
      "Transplant Hepatology",
    ],
  },
  {
    "Medical genetics": [
      "Biochemical Genetics",
      "Clinical Cytogenetics",
      "Clinical Genetics",
      "Molecular Genetic Pathology",
    ],
  },
  {
    Neurology: [
      "Brain Injury Medicine",
      "child Neurology",
      "Clinical Neurophysiology",
      "Endovascular Surgical Neuroradiology",
      "Hospice and Palliative Medicine",
      "Neurodevelopmental Disabilities",
      "Neuromuscular Medicine",
      "Pain Medicine",
      "Sleep Medicine",
      "Vascular Neurology",
    ],
  },
  {
    "Nuclear Medicine": null,
  },
  {
    "Obstetrics and Gynecology": [
      "Female Pelvic Medicine and Reconstructive Surgery",
      "Gynecologic Oncology",
      "Maternal-fetal Medicine",
      "Reproductive Endocrinologists and Infertility",
    ],
  },
  {
    Ophthalmology: [
      "Anterior Segment/Cornea Ophthalmology",
      "Glaucoma Ophthalmology",
      "Neuro-ophthalmology",
      "Ocular oncology",
      "Oculoplastics/Orbit",
      "Ophthalmic Plastic and Reconstructive Surgery",
      "Retina/Uveitis",
      "Strabismus/Pediatric Ophthalmology",
    ],
  },
  {
    Pathology: [
      "Anatomical Pathology",
      "Blood Banking and Transfusion Medicine",
      "Chemical Pathology",
      "Clinical Pathology",
      "Cytopathology",
      "Forensic Pathology",
      "Genetic Pathology",
      "Hematology",
      "Immunopathology",
      "Medical Microbiology",
      "Molecular Pathology",
      "Neuropathology",
      "Pediatric Pathology",
    ],
  },
  {
    Pediatrics: [
      "Adolescent Medicine",
      "Child Abuse Pediatrics",
      "Developmental-behavioral Pediatrics",
      "Neonatal-perinatal Medicine",
      "Pediatric Cardiology",
      "Pediatric Critical Care Medicine",
      "Pediatric Endocrinology",
      "Pediatric Gastroenterology",
      "Pediatric Hematology-oncology",
      "Pediatric Infectious diseases",
      "Pediatric Nephrology",
      "Pediatric Pulmonology",
      "Pediatric Rheumatology",
      "Pediatric Sports Medicine",
      "Pediatric Transplant Hepatology",
    ],
  },
  {
    "Physical Medicine and rehabilitation": [
      "Brain Injury Medicine",
      "Hospice and Palliative Medicine",
      "Neuromuscular Medicine",
      "Pain Medicine",
      "Pediatric Rehabilitation Medicine",
      "Spinal Cord Injury Medicine",
      "Sports Medicine",
    ],
  },
  {
    "Preventive Medicine": [
      "Aerospace Medicine",
      "Medical Toxicology",
      "Occupational Medicine",
      "Public Health Medicine",
    ],
  },
  {
    Psychiatry: [
      "Addiction Psychiatry",
      "Administrative Psychiatry",
      "Child and Adolescent Psychiatry",
      "Community Psychiatry",
      "Consultation/liaison Psychiatry",
      "Emergency Psychiatry",
      "Forensic Psychiatry",
      "Geriatric Psychiatry",
      "Mental Retardation Psychiatry",
      "Military Psychiatry",
      "Pain Medicine",
      "Psychiatric Research",
      "Psychosomatic Medicine",
    ],
  },
  {
    "Radiation Oncology": ["Hospice and Palliative Medicine", "Pain Medicine"],
  },
  {
    surgery: [
      "Colon and Rectal Surgery",
      "General Surgery",
      "Surgical Critical Care",
      "Gynecologic Oncology",
      "Plastic Surgery",
      "Craniofacial Surgery",
      "Hand Surgery",
      "Nerulogical Surgery",
      "Endovascular Surgical Neuroradiology",
      "Ophthalmic Surgery",
      "Oral and Maxillofacial Surgery",
      "Orthopaedic Surgery",
      "Adult Reconstructive Orthopaedics",
      "Foot and Ankle Orthopaedics",
      "Musculoskeletal Oncology",
      "Orthopaedic Sports Medicine",
      "Orthopaedic Surgery of the Spine",
      "Orthopaedic Trauma",
      "Pediatric Orthopaedics",
      "Otolaryngology",
      "Pediatric Otolaryngology",
      "Otology Neurotology",
      "Pediatric Surgery",
      "Neonatal Surgery",
      "Prenatal Surgery",
      "Trauma Surgery",
      "Pediatric Oncology",
      "Thoracic Surgery",
      "Congenital Cardiac Surgery",
      "Thoracic Surgery-integrated",
      "Vascular Surgery",
    ],
  },
  {
    Urology: [
      "Pediatric Urology",
      "Urologic Oncology",
      "Renal Transplant",
      "Male Infertility",
      "Calculi",
      "Female Urology",
      "Neurourology",
    ],
  },
];

module.exports = MedicalSpecialties;
